refactor currentId

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -1,88 +1,88 @@
-#name: Java CI
-#
-#on:
-#  push:
-#    branches: [ main, master ]
-#  pull_request:
-#    branches: [ main, master ]
-#  workflow_dispatch:
-#    inputs:
-#      deployment_target:
-#        description: Choose target
-#        required: true
-#        default: 'all_tests'
-#        type: choice
-#        options:
-#          - 'all_tests'
-#          - 'login_users'
-#
-#jobs:
-#  test:
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#      - name: Checkout repository
-#        uses: actions/checkout@v4
-#
-#      # ! Installation Java
-#      - name: Set up JDK 11
-#        uses: actions/setup-java@v3
-#        with:
-#          distribution: 'temurin'
-#          java-version: '11'
-#
-#      - name: Grant execute permission for gradlew
-#        run: chmod +x gradlew
-#
-#      # ! Installation of Chrome and ChromeDriver
-#      - name: Install Chrome
-#        run: |
-#          sudo apt-get update
-#          sudo apt-get install -y google-chrome-stable
-#
-#      - name: Install ChromeDriver
-#        run: |
-#          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
-#          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
-#          unzip chromedriver_linux64.zip -d /home/runner
-#          sudo mv -f /home/runner/chromedriver /usr/local/bin/chromedriver
-#          sudo chmod +x /usr/local/bin/chromedriver
-#
-#      # ! List of folders before tests
-#      - name: ✅ 📂 List Directories before tests
-#        if: always()
-#        run: ls -R
-#
-#      # ! Verify currentId.txt file location
-#      - name: Verify currentId.txt file location
-#        run: |
-#          if [ -f src/test/resources/currentId.txt ]; then
-#            echo "currentId.txt file found in src/test/resources"
-#          else
-#            echo "currentId.txt file not found in src/test/resources"
-#            exit 1
-#          fi
-#
-#      # ! Build with Gradle
-#      - name: Build with Gradle
-#        run: ./gradlew build
-#        continue-on-error: true
-#
-#      # ! Run tests
-#      - name: Run tests
-#        if: success() || failure()
-#        run: ./gradlew test
-#        continue-on-error: true
-#
-#      # ! List of folders after tests
-#      - name: ✅ 📂 List Directories after tests
-#        if: always()
-#        run: ls -R
-#
-#      # ! Upload Gradle Report
-#      - name: ✅ 📦 Archive [Test reports]
-#        uses: actions/upload-artifact@v2
-#        if: always()
-#        with:
-#          name: test-reports
-#          path: build/reports/tests/test/
+name: Java CI
+
+on:
+  push:
+    branches: [ main, master ]
+  pull_request:
+    branches: [ main, master ]
+  workflow_dispatch:
+    inputs:
+      deployment_target:
+        description: Choose target
+        required: true
+        default: 'all_tests'
+        type: choice
+        options:
+          - 'all_tests'
+          - 'login_users'
+
+jobs:
+  test:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      # ! Installation Java
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '11'
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
+
+      # ! Installation of Chrome and ChromeDriver
+      - name: Install Chrome
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y google-chrome-stable
+
+      - name: Install ChromeDriver
+        run: |
+          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
+          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
+          unzip chromedriver_linux64.zip -d /home/runner
+          sudo mv -f /home/runner/chromedriver /usr/local/bin/chromedriver
+          sudo chmod +x /usr/local/bin/chromedriver
+
+      # ! List of folders before tests
+      - name: ✅ 📂 List Directories before tests
+        if: always()
+        run: ls -R
+
+      # ! Verify currentId.txt file location
+      - name: Verify currentId.txt file location
+        run: |
+          if [ -f src/test/resources/currentId.txt ]; then
+            echo "currentId.txt file found in src/test/resources"
+          else
+            echo "currentId.txt file not found in src/test/resources"
+            exit 1
+          fi
+
+      # ! Build with Gradle
+      - name: Build with Gradle
+        run: ./gradlew build
+        continue-on-error: true
+
+      # ! Run tests
+      - name: Run tests
+        if: success() || failure()
+        run: ./gradlew test
+        continue-on-error: true
+
+      # ! List of folders after tests
+      - name: ✅ 📂 List Directories after tests
+        if: always()
+        run: ls -R
+
+      # ! Upload Gradle Report
+      - name: ✅ 📦 Archive [Test reports]
+        uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          name: test-reports
+          path: build/reports/tests/test/
