move currentId

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -15,20 +15,20 @@ on:
         options:
           - 'all_tests'
           - 'login_users'
+
 jobs:
   test:
-
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      # !  Installation Java
+      # ! Installation Java
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
-          distribution: 'temurin' # Опция также включает zulu, adopt, j9, etc.
+          distribution: 'temurin'
           java-version: '11'
 
       - name: Grant execute permission for gradlew
@@ -52,6 +52,16 @@ jobs:
       - name: ✅ 📂 List Directories before tests
         if: always()
         run: ls -R
+
+      # ! Verify currentId.txt file location
+      - name: Verify currentId.txt file location
+        run: |
+          if [ -f src/test/resources/currentId.txt ]; then
+            echo "currentId.txt file found in src/test/resources"
+          else
+            echo "currentId.txt file not found in src/test/resources"
+            exit 1
+          fi
 
       # ! Build with Gradle
       - name: Build with Gradle
